### PR TITLE
Personal portfolio

### PR DESCRIPTION
**Pull request by Hasinarahman**
This project is about my portfolio.
- first adding new repo
- clone the repo in VS code
- then adding html and css file 
- creating navbar for page 
- adding welcome section
- adding about section
- Project section
- adding contact us section 
- style the all these 
- making responsive the page
- adding linters file
- push these thing in github

### CODE REVIEW

**Comment by Hasinarahman** [comment]
> This project is about my portfolio.
> 
> * first adding new repo
> * clone the repo in VS code
> * then adding html and css file
> * creating navbar for page
> * adding welcome section
> * adding about section
> * Project section
> * adding contact us section
> * style the all these
> * making responsive the page
> * adding linters file
> * push these thing in github

**Comment by Hasinarahman** [comment]
new p

**Comment by Hasinarahman** [comment]
Hello sir @ahzamir,
My portfolio project is done please check it and give me your idea or feedback.

**Comment by Hasinarahman** [comment]
Hi sir @ahzamir
my project is ready for your review please give me feedback.

**Review by ahzamir — APPROVED** [review]
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Your project passes all checks on freecodecamp and will be considered as an approved project but it's not be counted as your capstone project as it is not responsive and have lots of issues for capstone project.

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done gre
Screenshot 2024-06-06 212329
at design Implemented. 🎯🎉👍


# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Personal Portfolio project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Hasinarahman** [comment]
ok thanks sir

**Pull request merged**
